name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🆕 Features"
    labels: ["feature", "enhancement"]
  - title: "🐞 Fixes"
    labels: ["bug", "fix"]
  - title: "🧪 Tests"
    labels: ["test"]
  - title: "🐳 CI/CD & Docker"
    labels: ["ci", "docker"]
  - title: "🧹 Maintenance"
    labels: ["chore", "refactor"]
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
template: |
  ## Changes
  $CHANGES