# Dockerfile.ci
FROM python:3.8-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#Copy app
COPY . .

# Set environment variable for Django
ENV DJANGO_SETTINGS_MODULE=network_ops_dashboard.settings
ENV PYTHONUNBUFFERED=1

# Run tests (can override in Github Actions if needed)
CMD ["pytest", "src"]