"""
Django settings for network_ops_dashboard project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
import logging.config # noqa: F401
from django.utils.log import DEFAULT_LOGGING # noqa: F401
from network_ops_dashboard.secrets import SECRET_KEY, DEBUG, ALLOWED_HOSTS, LOGGING, CRON_USER # noqa: F401

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# '..project_venv/'
VENV_DIR = Path(__file__).resolve().parent.parent.parent
# '..project_venv/src/'
BASE_DIR = Path(__file__).resolve().parent.parent
# '..project_venv/src/network_ops_dashboard/'
DJANGO_ROOT = os.path.join(os.path.dirname(os.path.realpath(__file__)))
# '..project_venv/src/network_ops_dashboard/../'
PROJECT_ROOT = os.path.join(DJANGO_ROOT, '..')
# manage.py 
MANAGE_PY = os.path.join(BASE_DIR, "manage.py")
# venv python bin
PYTHON_BIN = os.path.join(VENV_DIR, "bin", "python")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'network_ops_dashboard',
    'widget_tweaks',
    'django_cryptography',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'network_ops_dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'network_ops_dashboard.context_processors.site_settings_context',
                "network_ops_dashboard.context_processors.user_group_health",
            ],
        },
    },
]

WSGI_APPLICATION = 'network_ops_dashboard.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Central'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# '/django/venv/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATIC_URL = '/static/'

# '/django/venv/media/'
MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')
MEDIA_URL = '/media/'

# '/django/venv/protected_media/'
PROTECTED_MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'protected_media')

ADMIN_MEDIA_PREFIX = '/static/admin'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'